version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seacollect-web
    image: registry.seacotec.com/seacotools:21.1.3
    restart: unless-stopped
    ports:
      - "4200:80"


# build app
# docker compose build
# docker compose push
